import { UserSettings } from '@/types'

export const DEFAULT_SETTINGS: UserSettings = {
  calorie_goal: 2000,
  protein_goal: 75,
  carbs_goal: 250,
  fat_goal: 65,
  height: 170,
  weight: 65,
  age: 25,
  gender: 'male',
  goal: 'maintain',
}

export const MOCK_FOODS = [
  {
    food_name: '滷雞腿便當',
    food_name_en: 'Braised Chicken Leg Bento',
    calories: 650,
    protein: 28.5,
    carbs: 72.3,
    fat: 22.1,
    fiber: 3.2,
    serving_size: '1 份 (約 500g)',
    confidence: 0.87,
  },
  {
    food_name: '蛋炒飯',
    food_name_en: 'Egg Fried Rice',
    calories: 480,
    protein: 14.2,
    carbs: 68.5,
    fat: 16.8,
    fiber: 1.5,
    serving_size: '1 碗 (約 350g)',
    confidence: 0.92,
  },
  {
    food_name: '水煮雞胸沙拉',
    food_name_en: 'Poached Chicken Breast Salad',
    calories: 280,
    protein: 35.0,
    carbs: 12.4,
    fat: 8.6,
    fiber: 6.2,
    serving_size: '1 份 (約 300g)',
    confidence: 0.85,
  },
  {
    food_name: '豚骨拉麵',
    food_name_en: 'Tonkotsu Ramen',
    calories: 520,
    protein: 22.0,
    carbs: 65.0,
    fat: 18.5,
    fiber: 2.8,
    serving_size: '1 碗 (約 450g)',
    confidence: 0.79,
  },
  {
    food_name: '燕麥粥',
    food_name_en: 'Oatmeal',
    calories: 180,
    protein: 6.5,
    carbs: 32.0,
    fat: 3.2,
    fiber: 4.5,
    serving_size: '1 碗 (約 250ml)',
    confidence: 0.94,
  },
  {
    food_name: '起司牛肉漢堡',
    food_name_en: 'Cheeseburger',
    calories: 540,
    protein: 28.0,
    carbs: 42.0,
    fat: 26.0,
    fiber: 2.0,
    serving_size: '1 個 (約 200g)',
    confidence: 0.88,
  },
] as const
